---

- name: Install Keystone and Apache on Ubuntu
  apt:
    name:
      - keystone
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Starting/Enabling Keystone on Ubuntu
  service:
    name: apache2
    state: started
    enabled: true
  when: ansible_distribution == "Ubuntu"

- name: Install Keystone on CentOS
  yum:
    name:
      - openstack-keystone
      - httpd
      - mod_wsgi
    state: latest
  when: ansible_distribution == "CentOS"

- name: Starting/Enabling Keystone
  service:
    name: httpd.service
    state: started
    enabled: true
  when: ansible_distribution == "CentOS"
